# Generated by Django 5.2.16 on 2026-09-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babies', '0006_alter_baby_enrolled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Current height in cm', max_digits=4, null=True),
        ),
    ]
