# Generated by Django 5.2.16 on 2026-08-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='belt',
            name='nickname',
            field=models.CharField(blank=True, help_text="Friendly display name, e.g. 'Emma's belt'", max_length=64),
        ),
    ]
