# Generated by Django 5.2.16 on 2026-09-30 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='spo2',
        ),
        migrations.AddField(
            model_name='measurement',
            name='respiratory_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
