# Generated by Django 5.2.16 on 2026-09-30 19:14
"""SpO2 and movement are no longer measured (the belt now reports a
respiratory rate): drop alerts of the retired types, then narrow the choices."""

from django.db import migrations, models

RETIRED_TYPES = ["low_oxygen", "no_movement"]


def delete_retired_alerts(apps, schema_editor):
    Alert = apps.get_model("alerts", "Alert")
    Alert.objects.filter(type__in=RETIRED_TYPES).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alert_resolved_by'),
    ]

    operations = [
        migrations.RunPython(delete_retired_alerts, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('high_temp', 'High Temp'), ('low_temp', 'Low Temp'), ('high_hr', 'High Hr'), ('low_hr', 'Low Hr'), ('high_resp', 'High Resp'), ('low_resp', 'Low Resp'), ('belt_removed', 'belt Removed'), ('battery_low', 'Battery Low'), ('ble_lost', 'Ble Lost'), ('no_data', 'No Data')], max_length=24),
        ),
    ]
